
[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["logbook://auth-callback"]
enable_manual_linking = true
enable_anonymous_sign_ins = true
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits_symbols"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[functions.remote-signing-complete]
enabled = true
verify_jwt = false
import_map = "./functions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/remote-signing-complete/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/remote-signing-complete/*.html" ]

[functions.remote-signing-request]
enabled = true
verify_jwt = false
import_map = "./functions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/remote-signing-request/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/remote-signing-request/*.html" ]
