// Mock data for RALKREDUX prototype.
// Mirrors the real types in src/domain/logbook/types.ts but with frozen demo values.

const MOCK_PROFILE = {
  full_name: 'Eli K. Voss',
  primary_scheme: 'sprat',
  sprat_id: 'SPRAT-78421',
  sprat_level: 'II',
  sprat_expires_on: '2027-03-14',
  irata_id: 'IRATA-IT/27/19488',
  irata_level: 'I',
  irata_expires_on: '2026-09-02',
  employer: 'Vertical North Industrial',
  hours_career: 2148,
};

const MOCK_ENTRIES = [
  {
    id: 'e009',
    date_from: '2026-05-16',
    date_to: '2026-05-16',
    site: 'BP Whiting · Tank 47B',
    employer: 'Vertical North Industrial',
    client: 'BP Refining',
    work_task: 'NDT Inspection',
    access_method: 'Rope access · single rope',
    structure_type: 'Storage tank',
    description: 'External shell UT readings at 4 elevations, weld scan W-17 → W-22.',
    work_hours: 7.5,
    max_height: 38,
    height_unit: 'm',
    status: 'draft',
    pending_chain: true,
    gear: ['g_har_avao', 'g_rope_iridium', 'g_desc_rig', 'g_helmet_vertex'],
    witnesses: 0,
  },
  {
    id: 'e008',
    date_from: '2026-05-15',
    date_to: '2026-05-15',
    site: 'BP Whiting · Tank 47B',
    employer: 'Vertical North Industrial',
    client: 'BP Refining',
    work_task: 'NDT Inspection',
    access_method: 'Rope access · single rope',
    structure_type: 'Storage tank',
    description: 'Coupon mapping, magnetic particle on N-side seams.',
    work_hours: 8.0,
    max_height: 38,
    height_unit: 'm',
    status: 'signed',
    signature: {
      supervisor_name: 'Marisol Kerr',
      supervisor_scheme: 'sprat',
      supervisor_cert_number: 'SPRAT-44190 · L-III',
      signed_at: '2026-05-15T19:42:11Z',
      method: 'local',
      chain_hash: '3f9a1c54a7b1d220',
      previous_chain_hash: 'a1188b2c4d3e9d10',
    },
  },
  {
    id: 'e007',
    date_from: '2026-05-14',
    date_to: '2026-05-14',
    site: 'BP Whiting · Tank 47B',
    employer: 'Vertical North Industrial',
    client: 'BP Refining',
    work_task: 'Rig & Pre-Job',
    access_method: 'Rope access · double rope',
    structure_type: 'Storage tank',
    description: 'Anchor survey, two-rope deployment, fall-arrest drill.',
    work_hours: 6.0,
    max_height: 38,
    height_unit: 'm',
    status: 'signed',
    signature: {
      supervisor_name: 'Marisol Kerr',
      supervisor_scheme: 'sprat',
      supervisor_cert_number: 'SPRAT-44190 · L-III',
      signed_at: '2026-05-14T18:21:00Z',
      method: 'local',
      chain_hash: 'a1188b2c4d3e9d10',
      previous_chain_hash: '7e5d3a9c2b14ff08',
    },
  },
  {
    id: 'e006',
    date_from: '2026-05-12',
    date_to: '2026-05-12',
    site: 'Cypress Wind · WTG-14',
    employer: 'Vertical North Industrial',
    client: 'Cypress Renewables',
    work_task: 'Blade Repair',
    access_method: 'Rope access · single rope',
    structure_type: 'Wind turbine',
    description: 'LE bonding repair, low-pressure side, station 19.4m.',
    work_hours: 9.25,
    max_height: 84,
    height_unit: 'm',
    status: 'signed',
    signature: {
      supervisor_name: 'Dorian Sato',
      supervisor_scheme: 'irata',
      supervisor_cert_number: 'IRATA/IT-31-22118 · L-III',
      signed_at: '2026-05-12T20:11:08Z',
      method: 'remote',
      chain_hash: '7e5d3a9c2b14ff08',
      previous_chain_hash: '12bc9a87341c0066',
    },
  },
  {
    id: 'e005',
    date_from: '2026-05-08',
    date_to: '2026-05-08',
    site: 'Skye Tower 1',
    employer: 'Vertical North Industrial',
    client: 'Skye Property Group',
    work_task: 'Facade Cleaning',
    access_method: 'Rope access · single rope',
    structure_type: 'High-rise',
    description: 'East facade, floors 21–28, soft brush + neutral solvent.',
    work_hours: 7.0,
    max_height: 96,
    height_unit: 'm',
    status: 'signed',
    signature: {
      supervisor_name: 'Marisol Kerr',
      supervisor_scheme: 'sprat',
      supervisor_cert_number: 'SPRAT-44190 · L-III',
      signed_at: '2026-05-08T17:55:30Z',
      method: 'local',
      chain_hash: '12bc9a87341c0066',
      previous_chain_hash: 'b3a8f1990e1d5544',
    },
  },
  {
    id: 'e004',
    date_from: '2026-05-04',
    date_to: '2026-05-04',
    site: 'Skye Tower 1',
    employer: 'Vertical North Industrial',
    client: 'Skye Property Group',
    work_task: 'Facade Cleaning',
    access_method: 'Rope access · single rope',
    structure_type: 'High-rise',
    description: 'East facade, floors 12–20.',
    work_hours: 6.75,
    max_height: 96,
    height_unit: 'm',
    status: 'amended',
    signature: {
      supervisor_name: 'Marisol Kerr',
      supervisor_scheme: 'sprat',
      supervisor_cert_number: 'SPRAT-44190 · L-III',
      signed_at: '2026-05-04T18:02:11Z',
      method: 'local',
      chain_hash: 'b3a8f1990e1d5544',
      previous_chain_hash: '4a99c1e2f0773311',
    },
  },
];

const MOCK_GEAR = [
  {
    id: 'g_har_avao',
    name: 'AVAO BOD CROLL Fast',
    category: 'harness',
    manufacturer: 'Petzl',
    model: 'C71CFA 1',
    serial_number: '24A0091823',
    next_inspection_due: '2026-08-12',
    status: 'current',
    days_to_inspection: 87,
    last_inspected: '2026-02-12',
  },
  {
    id: 'g_helmet_vertex',
    name: 'Vertex Vent',
    category: 'helmet',
    manufacturer: 'Petzl',
    model: 'A010CA00',
    serial_number: '22F4501',
    next_inspection_due: '2026-05-28',
    status: 'due_soon',
    days_to_inspection: 11,
    last_inspected: '2025-11-28',
  },
  {
    id: 'g_rope_iridium',
    name: 'Iridium 11mm',
    category: 'rope',
    manufacturer: 'Beal',
    model: 'BC110I',
    serial_number: 'BL-2410-7741 · 60m',
    next_inspection_due: '2026-05-19',
    status: 'due_soon',
    days_to_inspection: 2,
    last_inspected: '2025-11-19',
  },
  {
    id: 'g_desc_rig',
    name: 'RIG Descender',
    category: 'descender',
    manufacturer: 'Petzl',
    model: 'D021AA01',
    serial_number: '23E22001',
    next_inspection_due: '2026-07-01',
    status: 'current',
    days_to_inspection: 45,
    last_inspected: '2026-01-01',
  },
  {
    id: 'g_asc_basic',
    name: 'BASIC Ascender',
    category: 'ascender',
    manufacturer: 'Petzl',
    model: 'B18BAA',
    serial_number: '21A5567',
    next_inspection_due: '2026-04-22',
    status: 'overdue',
    days_to_inspection: -25,
    last_inspected: '2025-10-22',
  },
  {
    id: 'g_carab_omni',
    name: 'OMNI TRIACT-LOCK',
    category: 'carabiner',
    manufacturer: 'Petzl',
    model: 'M37 TL',
    serial_number: '22C880',
    next_inspection_due: '2027-01-12',
    status: 'current',
    days_to_inspection: 240,
    last_inspected: '2026-01-12',
  },
  {
    id: 'g_lan_jane',
    name: 'JANE Lanyard',
    category: 'lanyard',
    manufacturer: 'Petzl',
    model: 'L52',
    serial_number: '24B0014',
    next_inspection_due: '2026-09-30',
    status: 'current',
    days_to_inspection: 136,
    last_inspected: '2026-03-30',
  },
  {
    id: 'g_pulley_micro',
    name: 'Micro Traxion',
    category: 'pulley',
    manufacturer: 'Petzl',
    model: 'P53A',
    serial_number: '23A7711',
    next_inspection_due: null,
    status: 'unscheduled',
    days_to_inspection: null,
    last_inspected: null,
  },
];

const GEAR_ICON = {
  harness: 'IconHarness',
  helmet: 'IconHelmet',
  rope: 'IconRope',
  carabiner: 'IconCarabiner',
  descender: 'IconDescender',
  ascender: 'IconCarabiner',
  lanyard: 'IconRope',
  sling: 'IconRope',
  pulley: 'IconDescender',
  other: 'IconCarabiner',
};

// Chain visualization data — short history of last 6 signatures.
const MOCK_CHAIN = [
  { hash: '3f9a1c54', date: '2026-05-15', label: 'Tank 47B · NDT' },
  { hash: 'a1188b2c', date: '2026-05-14', label: 'Tank 47B · Rig' },
  { hash: '7e5d3a9c', date: '2026-05-12', label: 'WTG-14 · LE Repair' },
  { hash: '12bc9a87', date: '2026-05-08', label: 'Skye 1 · Facade' },
  { hash: 'b3a8f199', date: '2026-05-04', label: 'Skye 1 · Facade' },
  { hash: '4a99c1e2', date: '2026-04-30', label: 'WTG-09 · Inspection' },
];

const MOCK_SUMMARY = {
  hours_week: 30.75,
  hours_month: 142.5,
  hours_career: 2148,
  entries_career: 287,
  drafts_pending: 1,
  awaiting_signature: 1,
  gear_overdue: 1,
  gear_due_soon: 2,
  cert_warning: 'IRATA expires in 108d',
  chain_head: '3f9a1c54a7b1d220',
  sync_state: 'queued', // 'synced' | 'syncing' | 'queued' | 'offline'
  queued_count: 1,
};

const SITE_RECENTS = ['BP Whiting · Tank 47B', 'Cypress Wind · WTG-14', 'Skye Tower 1', 'Newark Bridge · Span 4'];
const CLIENT_RECENTS = ['BP Refining', 'Cypress Renewables', 'Skye Property Group', 'NJTA'];
const TASK_CATALOG = ['NDT Inspection', 'Welding', 'Blade Repair', 'Facade Cleaning', 'Coatings', 'Rigging', 'Rescue Drill', 'Survey'];
const STRUCTURE_CATALOG = ['Storage tank', 'Wind turbine', 'High-rise', 'Bridge', 'Stack', 'Antenna', 'Dam'];
const ACCESS_CATALOG = ['Rope access · single rope', 'Rope access · double rope', 'Twin-tension', 'Pre-rigged platform', 'Suspended platform'];

Object.assign(window, {
  MOCK_PROFILE, MOCK_ENTRIES, MOCK_GEAR, MOCK_CHAIN, MOCK_SUMMARY,
  GEAR_ICON, SITE_RECENTS, CLIENT_RECENTS, TASK_CATALOG, STRUCTURE_CATALOG, ACCESS_CATALOG,
});
